# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paras',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
