# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_jain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jain',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
