# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20180507_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paras',
            old_name='name',
            new_name='Spoj_Handle',
        ),
    ]
