# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20180508_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
    ]
